version: '3.9'
services:
  certs-installer:
    build: .
    image: certs-installer-image
    volumes:
      - dotnet_data:/root/.dotnet
    command: ["/usr/local/bin/import-certs.sh"]

  myservice:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    volumes:
      - dotnet_data:/root/.dotnet
    depends_on:
      - certs-installer
    # If your application needs to use the certs, it can now find them in /root/.dotnet

volumes:
  dotnet_data: