version: '3.9'
services:
  certs-installer:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    # Mount the host script into the container
    volumes:
      - dotnet_data:/root/.dotnet
      - ./import-certs.sh:/usr/local/bin/import-certs.sh:ro
    # Run the script at startup
    command: ["/bin/bash", "/usr/local/bin/import-certs.sh"]

  myservice:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    volumes:
      - dotnet_data:/root/.dotnet
    depends_on:
      - certs-installer
    # At this point, myservice has access to /root/.dotnet 
    # which contains the installed tool and trusted certificates

volumes:
  dotnet_data: